sectionPagesMenu = "main"

baseURL = 'https://astridmalter.com/'
languageCode = 'en-us'
title = 'Astrid Malter'

backgroundImage = '/content/noguchi.jpg'

hideColorSchemeToggle = true
theme = 'hugo-theme-ava'

[menu]
[[menu.main]]
  name = 'Projects'
  url = '/projects'
  weight = 50
[[menu.main]]
  name = 'About'
  url = '/about'
  weight = 50
[[menu.main]]
  name = 'Contact'
  url = '/contact'
  weight = 50
